import Link from "next/link";
import { Download, Share2, Sparkles, FileText, Printer } from "lucide-react";
import { Metadata } from "next";

type Props = {
  params: Promise<{ reportId: string }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { reportId } = await params;
  const brandName = reportId.charAt(0).toUpperCase() + reportId.slice(1);
  
  return {
    title: `${brandName} AI Brand Analysis Report | Brand Monitor AI`,
    description: `Read the latest AI sentiment analysis for ${brandName}. See what ChatGPT, Gemini, and Grok are saying about this brand. Viral trends, sentiment score, and more.`,
    openGraph: {
      title: `${brandName} AI Brand Analysis | Brand Monitor AI`,
      description: `Detailed AI insight report for ${brandName}. Sentiment Score: 85/100. Viral Status: Trending.`,
      type: "article",
    },
  };
}

export default async function PublicReportPage({ params }: Props) {
  const { reportId } = await params;
  const brandName = reportId.charAt(0).toUpperCase() + reportId.slice(1);

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": `${brandName} AI Brand Analysis Report`,
    "datePublished": new Date().toISOString(),
    "author": {
      "@type": "Organization",
      "name": "Brand Monitor AI"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Brand Monitor AI",
      "logo": {
        "@type": "ImageObject",
        "url": "https://brandmonitor.ai/logo.png"
      }
    },
    "description": `Comprehensive AI sentiment analysis for ${brandName} generated by Brand Monitor AI.`
  };

  return (
    <div className="min-h-screen bg-black text-white p-6 md:p-12 font-sans">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      {/* Public Header */}
      <header className="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6 mb-12 border-b border-white/10 pb-8">
        <Link href="/" className="flex items-center gap-2 group">
          <div className="bg-neon-green text-black p-1.5 rounded-lg">
            <Sparkles size={20} strokeWidth={2.5} />
          </div>
          <span className="font-bold text-xl tracking-tight">
            BrandMonitor<span className="text-neon-purple">AI</span>
          </span>
        </Link>
        <div className="flex gap-3">
          <button className="btn btn-outline border-white/20 text-white hover:bg-white/10 gap-2">
            <Printer size={18} /> Print / PDF
          </button>
          <button className="btn btn-outline border-white/20 text-white hover:bg-white/10 gap-2">
            <FileText size={18} /> Download Word
          </button>
        </div>
      </header>

      {/* Report Content */}
      <main className="max-w-5xl mx-auto animate-fade-in-up">
        <div className="text-center mb-12">
          <div className="inline-block bg-white/5 px-4 py-1 rounded-full text-sm text-gray-400 mb-4 border border-white/10">
            Public AI Insight Report
          </div>
          <h1 className="text-5xl md:text-6xl font-bold mb-4">{brandName}</h1>
          <p className="text-xl text-gray-400">Generated on {new Date().toLocaleDateString()}</p>
        </div>

        {/* Executive Summary */}
        <div className="glass-panel p-8 rounded-3xl mb-8 border-l-4 border-neon-purple">
          <h2 className="text-2xl font-bold mb-4">Executive Summary</h2>
          <p className="text-gray-300 leading-relaxed text-lg">
            The overall sentiment for <strong>{brandName}</strong> is currently <span className="text-neon-green font-bold">Positive</span>. 
            AI models indicate a strong viral potential due to recent product launches. However, there are minor concerns regarding pricing mentioned on Reddit and X (Grok).
          </p>
        </div>

        {/* Stats Row */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="glass-panel p-6 rounded-2xl text-center">
            <div className="text-gray-400 mb-2">Sentiment Score</div>
            <div className="text-5xl font-bold text-neon-green">85<span className="text-lg text-gray-500">/100</span></div>
          </div>
          <div className="glass-panel p-6 rounded-2xl text-center">
            <div className="text-gray-400 mb-2">Mentions (24h)</div>
            <div className="text-5xl font-bold text-white">12.5k</div>
          </div>
          <div className="glass-panel p-6 rounded-2xl text-center">
            <div className="text-gray-400 mb-2">Viral Status</div>
            <div className="text-5xl font-bold text-neon-pink">Trending</div>
          </div>
        </div>

        {/* Detailed Analysis */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12">
          <div className="glass-panel p-8 rounded-3xl">
            <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-green-500"></span> What's Working
            </h3>
            <ul className="space-y-4">
              <li className="flex gap-3 text-gray-300">
                <span className="font-bold text-green-400">1.</span>
                Users love the new aesthetic and design language.
              </li>
              <li className="flex gap-3 text-gray-300">
                <span className="font-bold text-green-400">2.</span>
                ChatGPT praises the brand's innovation in sustainability.
              </li>
              <li className="flex gap-3 text-gray-300">
                <span className="font-bold text-green-400">3.</span>
                High engagement on TikTok related to the #NewDrop challenge.
              </li>
            </ul>
          </div>

          <div className="glass-panel p-8 rounded-3xl">
            <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-red-500"></span> Areas of Concern
            </h3>
            <ul className="space-y-4">
              <li className="flex gap-3 text-gray-300">
                <span className="font-bold text-red-400">1.</span>
                Grok highlights complaints about shipping delays.
              </li>
              <li className="flex gap-3 text-gray-300">
                <span className="font-bold text-red-400">2.</span>
                Some users feel the pricing is becoming exclusionary.
              </li>
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center text-gray-500 text-sm border-t border-white/10 pt-8">
          <p>Powered by Brand Monitor AI. Want to track your own brand?</p>
          <Link href="/register" className="text-neon-blue hover:underline mt-2 inline-block">
            Start Free Trial
          </Link>
        </div>
      </main>
    </div>
  );
}
